name: github_gists_app
description: applications for displaying gists working with Gihub api
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  hive: ^2.2.3
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  get_it: ^7.6.4
  extended_image: ^8.1.1
  flutter_animate: ^4.2.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true

